version: "3.7"

services:

  tezland-backend:
    container_name: tezland-backend
    image: tezland-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend-ipfs
      #- tezland-app # build fails with the dep

  #
  # We'll need an ipfs api entrypoint in prod.
  #
  backend-ipfs:
    container_name: backend-ipfs
    restart: always
    image: ipfs/go-ipfs:latest
    environment:
      #- IPFS_SWARM_KEY=/key/swarm/psk/1.0.0/\n/base16/\n925e93e58f6cb4aa7a5660e5166a3081f84d40a6888f70d49fdbc68f0f10362a
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./ipfsdata:/ipfsdata
      - ./docker-scripts/001-ipfs-init.sh:/container-init.d/001-ipfs-init.sh
    expose:
      - 4001/tcp
      - 4001/udp
      - 5001/tcp
      - 8080/tcp
      - 8081/tcp
    logging: &ipfs-logging
      options:
        max-size: 10m
        max-file: "5"

networks:
  default:
    name: tz1and_prod