version: "3.7"

services:

  tezland-backend:
    container_name: tezland-backend
    image: tezland-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend-ipfs
      #- tezland-app # build fails with the dep

  #
  # We'll need an ipfs api entrypoint in prod.
  #
  backend-ipfs:
    container_name: backend-ipfs
    restart: always
    image: ipfs/kubo:v0.15.0
    environment:
      - IPFS_PATH=/ipfsdata
    volumes:
      - ./ipfsdata:/ipfsdata
      - ./docker-scripts/001-ipfs-init.sh:/container-init.d/001-ipfs-init.sh
    ports:
      - "4001:4001"
      - "4001:4001/udp"
      - "127.0.0.1:5001:5001"
    logging: &ipfs-logging
      options:
        max-size: 10m
        max-file: "5"
    command: ["daemon", "--migrate=true", "--agent-version-suffix=docker", "--enable-gc"]

networks:
  default:
    name: tz1and_prod